### ISSUE TITLE
关于首页blog模块个人名片社交icon的设置

### ISSUE THREAD

**Issue by Undertone0809** [vuepress-reco/vuepress-theme-reco#137]
**Question & Description**

I would like to add blog module in home page. Adding my github and gitee icon to personal card. I add frontmatter following the tutorial but Xions website can not open. So I don't know how to set the icon.

![image](https://user-images.githubusercontent.com/72488598/196358688-0741b913-2fb8-4b51-9adf-7e722a93d2a4.png)

My code as following but nothing happen.

![image](https://user-images.githubusercontent.com/72488598/196359665-4a43ba00-230d-43c0-b12d-6a7066f4e28a.png)

![image](https://user-images.githubusercontent.com/72488598/196359835-76ec546a-c29d-41be-b840-5f022e464cfc.png)

**Additional context**

The document will looks better if some detail demo can be added.

**Comment by Undertone0809** [comment]
I have solve the problem. At first, I can not open the xicons website because of Internet. After some tries I enter the website and copy the icon name. But I don't know how to write yaml because the tutorial has no demo. So the only thing is seeing the source code. I know how to write it when I see `/src/client/componenets/Blog.vue` .
```yml
blog:
  socialLinks:
    - { icon: Github, link: 'http://www.baidu.com' }
    - { icon: BrandGithub, link: 'http://www.baidu.com' }
```
