### ISSUE TITLE
是否可以增加调整内容宽度的配置

### ISSUE THREAD

**Issue by woytu** [vuepress-reco/vuepress-theme-reco#141]
#### What problem does this feature solve?

内容显示宽度750px是否可以定义一个配置自定义调整

#### How should this be implemented in your opinion?

添加设置项修改[/styles/wrapper.styl下的max-width $contentWidth](https://github.com/vuepress-reco/vuepress-theme-reco/blob/748e560cd0de2cc8066b45e508756d81c4bb2336/styles/wrapper.styl#L2)

**Comment by woytu** [comment]
我自己找到解决方案了

按照官方目录结构说明 https://v1.vuepress.vuejs.org/zh/guide/directory-structure.html

添加` .vuepress/styles/index.styl` 文件，添加以下代码设置
```css
#app .page-title, #app .theme-reco-content.content__default, #app footer, #app .page-nav, #app .comments-wrapper {
    max-width: 960px;
}

#app .page-title {
    padding: 1.5rem;
}

#app .theme-reco-content.content__default {
    padding: 0rem 2.5rem;
}

#app .theme-reco-content.content__default > h1 {
    display: none;
}
```
