### ISSUE TITLE
Front Matter Date Option Must be UTC

### ISSUE THREAD

**Issue by jinmu333** [vuepress-reco/vuepress-theme-reco#305]
在  Front Matter 中使用本地时间 (UCT + 8)
渲染之后会再次 + 8
希望可以用配置项修改 时间的格式化

```md
---
title: Vuepress Blog
date: 2021-01-24 20:07:41
categories:
    - front
tags:
    - vuepress
---
```

![image](https://user-images.githubusercontent.com/32295532/105634217-ed586d00-5e97-11eb-9ad7-fcf5efa274b2.png)

 例如 @vuepress/last-updated  的自定义格式化
```js
          [
            '@vuepress/last-updated',
            {
              transformer: (timestamp, lang, dateOptions) => {
                 ...
              }
            }
          ],
```

- Your OS:  macos11.1
- Node.js version:  V15.6.0
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.1
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by jinmu333** [comment]
`vuepress` 在 `parseFrontmatter` 之后就是 `2019-09-28T13:55:36.000Z`这种格式了

**Comment by recoluan** [comment]
请使用 `string` 格式书写日期：
```yaml
---
title: Vuepress Blog
date: '2021-01-24 20:07:41'
categories:
    - front
tags:
    - vuepress
---
```
